# Author: Pyoung Kang Kim
# This is the deployment yaml file that defines the name of the deployment
# and the replica set which runs 3 replicas of the pod defined in the template,
# which internally uses the hw2-container from the image built from Dockerfile that I published to ECR

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw3-ui-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw3-ui
  template:
    metadata:
      labels:
        app: hw3-ui
    spec:
      containers:
        - name: hw3-ui-container
          image: 800617640166.dkr.ecr.us-east-1.amazonaws.com/hw3-ui:latest
          ports:
            - containerPort: 4200