apiVersion: v1
kind: Service
metadata:
  name: hw-np-service
spec:
  type: NodePort
  selector:
    app: hw2
  ports:
    # You'll be able to contact the NodePort Service, from outside the cluster, by requesting <NodeIP>:<NodePort>.
    - nodePort: 31479 # port used for external traffic
      port: 8081 # port for the service, cluster uses this port
      targetPort: 8080 # where the communication of external traffic goes to(where the container ports are)